//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograIV.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarPago", ReplyAction="http://tempuri.org/IService1/insertarPagoResponse")]
        void insertarPago(WCFProyectoPrograIV.Pago objPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarPago", ReplyAction="http://tempuri.org/IService1/insertarPagoResponse")]
        System.Threading.Tasks.Task insertarPagoAsync(WCFProyectoPrograIV.Pago objPago);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProyectoPrograIV.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProyectoPrograIV.ServiceReference1.IService1>, ProyectoPrograIV.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarPago(WCFProyectoPrograIV.Pago objPago) {
            base.Channel.insertarPago(objPago);
        }
        
        public System.Threading.Tasks.Task insertarPagoAsync(WCFProyectoPrograIV.Pago objPago) {
            return base.Channel.insertarPagoAsync(objPago);
        }
    }
}
